---
- name: Elasticsearch | Install unzip and java package
  yum: name={{ item }} state=installed
  when: ansible_os_family == "RedHat"
  tags: install
  with_items:
    - unzip
    - java-1.8.0-openjdk

- name: Elasticsearch | /etc/sysctl.conf
  sysctl: name="{{ item.name }}" value={{ item.value }} state=present sysctl_set=yes
  with_items:
    - {name: vm.swappiness,     value: 1     }
    - {name: vm.max_map_count,  value: 262144}
    - {name: fs.file-max,       value: 262144}
  tags: install

- name: Elasticsearch | Ensure Datadir
  file: name={{ es_datadir }} state=directory 

- name: Elasticsearch | Create Group
  group: name={{ es_name }} gid={{ es_uid }} state=present
  tags: install

- name: Elasticsearch | Create User
  user: name={{ es_name }} uid={{ es_uid }} home={{ es_dest_install_path }}/{{ es_name }} createhome=no system=yes
  tags: install
