---
- name: Elasticsearch | Install unzip and java package
  yum: name={{ item }} state=installed
  when: ansible_os_family == "RedHat"
  tags: install
  with_items:
    - unzip

- name: Elasticsearch | /etc/sysctl.conf
  sysctl: name="{{ item.name }}" value={{ item.value }} state=present sysctl_set=yes
  with_items:
    - {name: vm.swappiness,     value: 1     }
    - {name: vm.max_map_count,  value: 262144}
    - {name: fs.file-max,       value: 262144}
  tags: install

- name: Elasticsearch | Ensure Datadir
  file: name={{ es_datadir }} state=directory

- name: Elasticsearch | Create Group
  group: name={{ es_name }} gid={{ es_uid }} state=present
  tags: install

- name: Elasticsearch | Create User
  user: name={{ es_name }} uid={{ es_uid }} home={{ es_dest_install_path }}/{{ es_name }} createhome=no system=yes
  tags: install

- name: Elasticsearch | Check dir exists
  stat: path="{{ es_dest_install_path }}/{{ es_version }}" 
  register: es_dir_result
  tags: install

- name: Elasticsearch | Download and Install Package
  unarchive:
    src: "{{ es_src_pkg }}"
    dest: "{{ es_dest_install_path }}"
    remote_src: "{{ es_remote_src }}"
    keep_newer: yes
  when: not es_dir_result.stat.exists
  tags: install

- name: Elasticsearch | Ensure Link elasticsearch
  file: src="{{ es_dest_install_path }}/{{ es_version }}" dest="{{ es_dest_install_path }}/{{ es_name }}" state=link
  tags: install

- name: Elasticsearch | ADD bin directory in PATH
  lineinfile:
    dest: /etc/profile
    state: present
    regexp: 'export PATH=$PATH:*"{{ es_name }}"/bin'
    line: 'export PATH=$PATH:{{ es_dest_install_path }}/{{ es_name }}/bin'
    backrefs: yes
  tags: line

- name: Elasticsearch | Ajust Permission
  file: name="{{ item }}" owner={{ es_name }} group={{ es_name }} recurse=yes
  with_items:
    - "{{ es_dest_install_path }}/{{ es_version }}"
  tags: install
