# ======================== Elasticsearch Configuration =========================
cluster.name: graylog
#node.name: node-1
#node.attr.rack: r1
#path.data: /path/to/data
#path.logs: /path/to/logs
bootstrap.memory_lock: true
#network.host: 192.168.0.1
http.port: 9200
index.codec: best_compression
cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.low: 2gb
cluster.routing.allocation.disk.watermark.high: 4gb
#discovery.zen.ping.unicast.hosts: ["host1", "host2"]
#discovery.zen.minimum_master_nodes: 3
#gateway.recover_after_nodes: 3
#action.destructive_requires_name: true
